import { Head } from '@inertiajs/react';
import { DateField } from '../reports';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';

type Patient = { id: string; first_name: string; last_name: string; email: string; contact_number: string; status: string; created_at: string; clinics: Array<{ id: number; clinic_name: string }> };
type Props = { filters: { search?: string; status?: string; start_date?: string; end_date?: string }; patients: { data: Patient[]; links: Array<{ url: string | null; label: string; active: boolean }> } };

export default function PatientReport({ filters, patients }: Props) { return <><Head title="Patient list" /><main className="flex flex-1 flex-col gap-6 p-6"><header><h1 className="text-2xl font-semibold">Patient list</h1><p className="text-muted-foreground">Read-only patient directory filtered by registration date and status.</p></header>
    <form method="get" action="/admin/patients" className="flex flex-wrap items-end gap-3 rounded-lg border p-4"><Input name="search" placeholder="Search patients" defaultValue={filters.search ?? ''} className="w-56" /><Input name="status" placeholder="Status" defaultValue={filters.status ?? ''} className="w-36" /><DateField label="Created from" name="start_date" value={filters.start_date ?? ''} /><DateField label="Created to" name="end_date" value={filters.end_date ?? ''} /><Button type="submit">Apply filters</Button></form>
    <div className="overflow-x-auto rounded-lg border"><Table><TableHeader><TableRow>{['Created', 'Patient', 'Clinics', 'Email', 'Contact', 'Status'].map((h) => <TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{patients.data.map((patient) => <TableRow key={patient.id}><TableCell>{new Date(patient.created_at).toLocaleDateString()}</TableCell><TableCell>{patient.first_name} {patient.last_name}</TableCell><TableCell>{patient.clinics.map((clinic) => clinic.clinic_name).join(', ') || '—'}</TableCell><TableCell>{patient.email}</TableCell><TableCell>{patient.contact_number}</TableCell><TableCell>{patient.status}</TableCell></TableRow>)}{patients.data.length === 0 && <TableRow><TableCell colSpan={6} className="py-8 text-center text-muted-foreground">No patients found.</TableCell></TableRow>}</TableBody></Table></div><Pagination links={patients.links} /></main></>; }
function Pagination({ links }: { links: Props['patients']['links'] }) { return <nav className="flex flex-wrap gap-2">{links.map((link, i) => <a key={`${link.label}-${i}`} href={link.url ?? undefined} aria-disabled={!link.url} className={`rounded-md border px-3 py-2 text-sm ${link.active ? 'bg-primary text-primary-foreground' : ''} ${!link.url ? 'pointer-events-none opacity-50' : ''}`} dangerouslySetInnerHTML={{ __html: link.label }} />)}</nav>; }
